# =============================================================================
# EIGEN IAM — Thème Keycloak Central :: eigen-central
# Hérite du thème de base Keycloak et surcharge les templates et styles.
# =============================================================================

parent=keycloak
import=common/keycloak

# Activer les ressources locales
locales=fr,en

# Cache des ressources (désactiver en développement pour voir les changements)
# staticMaxAge=-1
# cacheTemplates=false
# cacheThemes=false
